In [32]:
import pandas as pd
import sys
sys.path.append("..")
from src.url_validator import normalize_url, check_url_reachability, validate_website

In [6]:
sample_big = pd.read_csv(
    "../data/processed/us_companies.csv",
    nrows=1000
)

sample_1 = sample_big.sample(100, random_state=42)
sample_1

,name,website,industry,size,type,city,state,country_code
521,Able Auto Body,ableautobodysurrey.com,motor vehicle manufacturing,1-10,NaN,New London,Connecticut,US
737,"Acklam, Inc.",acklaminc.com,civil engineering,11-50,Privately Held,Brighton,Colorado,US
740,ACME Credit Partners,acmecreditpartners.com,financial services,1-10,Privately Held,New York,New York,US
660,Accudyn,accudyn.com,plastics manufacturing,51-200,Privately Held,Erie,Pennsylvania,US
411,A.H. Levy & Co.,ahlevy.com,public policy,1-10,Privately Held,New,York,US
...,...,...,...,...,...,...,...,...
436,AAA BestWater Company,aaabestwater.com,renewable energy semiconductor manufacturing,1-10,Self-Owned,Kaneohe,Hawaii,US
764,"Across the Board Therapy Group, LLC",acrosstheboardtherapy.com,medical practices,11-50,Privately Held,Navarre,Florida,US
88,2020WonVision,2020wonvision.com,e-learning providers,1-10,Nonprofit,Delray Beach,Florida,US
63,One Promise Counseling and DUI Education,onepromiseoutpatient.org,mental health care,11-50,NaN,Baltimore,Maryland,US
826,Acurax,acuraxresearch.com,market research,11-50,Public Company,Houston,Texas,US

In [7]:
sample_1["website_normalized"] = sample_1["website"].apply(normalize_url)
sample_1[["name", "website", "website_normalized"]]

,name,website,website_normalized
521,Able Auto Body,ableautobodysurrey.com,https://ableautobodysurrey.com
737,"Acklam, Inc.",acklaminc.com,https://acklaminc.com
740,ACME Credit Partners,acmecreditpartners.com,https://acmecreditpartners.com
660,Accudyn,accudyn.com,https://accudyn.com
411,A.H. Levy & Co.,ahlevy.com,https://ahlevy.com
...,...,...,...
436,AAA BestWater Company,aaabestwater.com,https://aaabestwater.com
764,"Across the Board Therapy Group, LLC",acrosstheboardtherapy.com,https://acrosstheboardtherapy.com
88,2020WonVision,2020wonvision.com,https://2020wonvision.com
63,One Promise Counseling and DUI Education,onepromiseoutpatient.org,https://onepromiseoutpatient.org
826,Acurax,acuraxresearch.com,https://acuraxresearch.com

In [3]:
sample_1["website_normalized"].isna().sum()

KeyError: 'website_normalized'

In [8]:
sample_1[
    sample_1["website"] != sample_1["website_normalized"]
][["name", "website", "website_normalized"]]

,name,website,website_normalized
521,Able Auto Body,ableautobodysurrey.com,https://ableautobodysurrey.com
737,"Acklam, Inc.",acklaminc.com,https://acklaminc.com
740,ACME Credit Partners,acmecreditpartners.com,https://acmecreditpartners.com
660,Accudyn,accudyn.com,https://accudyn.com
411,A.H. Levy & Co.,ahlevy.com,https://ahlevy.com
...,...,...,...
436,AAA BestWater Company,aaabestwater.com,https://aaabestwater.com
764,"Across the Board Therapy Group, LLC",acrosstheboardtherapy.com,https://acrosstheboardtherapy.com
88,2020WonVision,2020wonvision.com,https://2020wonvision.com
63,One Promise Counseling and DUI Education,onepromiseoutpatient.org,https://onepromiseoutpatient.org
826,Acurax,acuraxresearch.com,https://acuraxresearch.com

URL format observation: In a random sample of 100 companies, all website values were stored as domain-only strings without an HTTP/HTTPS scheme. normalize_url() therefore added https:// to all sampled URLs, with no missing outputs.

In [9]:
sample_big["website"].str.contains("://", regex=False).sum()

0

In [10]:
sample_big[
    sample_big["website"].str.contains("/", regex=False)
][["name", "website"]]

Empty DataFrame
Columns: [name, website]
Index: []

The dataset's website field contains bare domains rather than complete URLs, so normalization only needs to add an HTTPS scheme and handle missing/invalid values.

In [11]:
sample_2 = sample_1.sample(25, random_state=42).copy()
sample_2

,name,website,industry,size,type,city,state,country_code,website_normalized
67,1ST Choice Energy Services,1stchoiceenergyservices.com,oil and gas,201-500,Public Company,New Philadelphia,Ohio,US,https://1stchoiceenergyservices.com
578,"Academic Research Associates, Inc.",fairygrantmother.com,writing and editing,1-10,Privately Held,Taylor,Texas,US,https://fairygrantmother.com
107,247 Dispatching Services,247dispatchingservices.com,truck transportation,1-10,Privately Held,Duluth,Georgia,US,https://247dispatchingservices.com
277,8S Solutions LLC,8ssolutionsllc.com,it services and it consulting,11-50,Partnership,Irving,Texas,US,https://8ssolutionsllc.com
299,"A&M Tool and Molding Corporation, Inc.",a-mtool.com,mining,1-10,NaN,Arden,North Carolina,US,https://a-mtool.com
59,1919 Design Co.,1919designco.com,design services,1-10,Self-Employed,Houston,Texas,US,https://1919designco.com
371,"A Network Service, Inc.",anetworkservice.com,computer networking,1-10,Privately Held,Boise,Idaho,US,https://anetworkservice.com
679,Accurate Upgrades LLC Kitchen & Bathroom Remod...,accurateupgrades.com,construction,1-10,Self-Owned,Salisbury,Maryland,US,https://accurateupgrades.com
811,Actor Boutique,actorboutique.com,entertainment,1-10,NaN,Atlanta,Georgia,US,https://actorboutique.com
521,Able Auto Body,ableautobodysurrey.com,motor vehicle manufacturing,1-10,NaN,New London,Connecticut,US,https://ableautobodysurrey.com
761,"Acres & Royalty, LLC",acresandroyalty.com,oil and gas,1-10,Privately Held,Ruston,Louisiana,US,https://acresandroyalty.com
346,A-Express Towing & Recovery,aexpresstowing.com,truck transportation,1-10,NaN,Palatine,Illinois,US,https://aexpresstowing.com
741,Acme Materials,acmebuildingmaterials.com,construction,1-10,NaN,Plano,Texas,US,https://acmebuildingmaterials.com
499,Abell Companions Inc,abellcompanions.com,government administration,11-50,NaN,Mc,Texas,US,https://abellcompanions.com
382,A Paper Trail,apapertrail.com,accounting,1-10,Self-Owned,Brownsville,Texas,US,https://apapertrail.com
411,A.H. Levy & Co.,ahlevy.com,public policy,1-10,Privately Held,New,York,US,https://ahlevy.com
652,Accounting Portfolios Inc,pachecotax.com,armed forces,1-10,NaN,Fall River,Massachusetts,US,https://pachecotax.com
39,123 Cash Offer,123cashoffer.com,real estate,1-10,Public Company,Areas,Arizona,US,https://123cashoffer.com
636,Accio Design LLC,acciodesign.me,design services,1-10,Self-Owned,NaN,NaN,US,https://acciodesign.me
139,3 Kitchens Catering,3kitchenscatering.com,hospitality,1-10,Self-Owned,Salem,Massachusetts,US,https://3kitchenscatering.com
30,Awearness Brand Apparel LLC,110creedapparel.com,retail apparel and fashion,1-10,Self-Employed,Norman,Oklahoma,US,https://110creedapparel.com
753,ACPC Health,acpchealth.com,hospitals and health care,1-10,Privately Held,Hoboken,New Jersey,US,https://acpchealth.com
101,22 Until Valhalla,22uv.org,armed forces,1-10,Nonprofit,Independence,Kentucky,US,https://22uv.org
312,A Abel Roofing & Siding,aabelroofing.com,construction,1-10,NaN,Dayton,Ohio,US,https://aabelroofing.com
543,Abrasive Supply Co,polyblast.com,plastics manufacturing,1-10,NaN,Minerva,Ohio,US,https://polyblast.com

In [12]:
reachability_results = sample_2["website_normalized"].apply(check_url_reachability)
reachability_results

67     {'accessible': True, 'http_status': 200, 'fina...
578    {'accessible': False, 'http_status': None, 'fi...
107    {'accessible': False, 'http_status': None, 'fi...
277    {'accessible': False, 'http_status': None, 'fi...
299    {'accessible': True, 'http_status': 200, 'fina...
59     {'accessible': True, 'http_status': 200, 'fina...
371    {'accessible': True, 'http_status': 200, 'fina...
679    {'accessible': False, 'http_status': None, 'fi...
811    {'accessible': False, 'http_status': None, 'fi...
521    {'accessible': True, 'http_status': 200, 'fina...
761    {'accessible': True, 'http_status': 200, 'fina...
346    {'accessible': False, 'http_status': None, 'fi...
741    {'accessible': True, 'http_status': 200, 'fina...
499    {'accessible': False, 'http_status': None, 'fi...
382    {'accessible': True, 'http_status': 200, 'fina...
411    {'accessible': True, 'http_status': 200, 'fina...
652    {'accessible': True, 'http_status': 200, 'fina...
39     {'accessible': True, 'http_status': 200, 'fina...
636    {'accessible': True, 'http_status': 200, 'fina...
139    {'accessible': False, 'http_status': None, 'fi...
30     {'accessible': False, 'http_status': None, 'fi...
753    {'accessible': False, 'http_status': None, 'fi...
101    {'accessible': True, 'http_status': 200, 'fina...
312    {'accessible': False, 'http_status': 403, 'fin...
543    {'accessible': True, 'http_status': 200, 'fina...
Name: website_normalized, dtype: object

In [14]:
reachability_df = pd.DataFrame(reachability_results.tolist())
reachability_df

,accessible,http_status,final_url,content_type,failure_reason,website_type
0,True,200.0,https://www.heritagecooperative.com/1st-choice...,text/html; charset=utf-8,None,company_website
1,False,NaN,None,None,connection_error,None
2,False,NaN,None,None,connection_error,None
3,False,NaN,None,None,connection_error,None
4,True,200.0,http://a-mtool-com.securec95biz.ezhostingserve...,text/html;charset=UTF-8,None,company_website
5,True,200.0,https://1919designco.com/,text/html,None,company_website
6,True,200.0,https://anetworkservice.com/,text/html,None,company_website
7,False,NaN,None,None,timeout,None
8,False,NaN,None,None,connection_error,None
9,True,200.0,https://ableautobodysurrey.com/,text/html; charset=UTF-8,None,company_website
10,True,200.0,https://nlanotary.com/,text/html; charset=utf-8,None,company_website
11,False,NaN,None,None,connection_error,None
12,True,200.0,https://www.qxo.com/welcome-to-beacon,text/html; charset=utf-8,None,company_website
13,False,NaN,None,None,connection_error,None
14,True,200.0,https://apapertrail.com/,text/html; charset=UTF-8,None,company_website
15,True,200.0,https://www.ahlevy.com/,text/html;charset=utf-8,None,company_website
16,True,200.0,https://pachecotax.com/,text/html; charset=UTF-8,None,company_website
17,True,200.0,https://123cashoffer.com/,text/html; charset=UTF-8,None,company_website
18,True,200.0,https://www.acciodesign.me/,text/html;charset=utf-8,None,company_website
19,False,NaN,None,None,connection_error,None
20,False,NaN,None,None,connection_error,None
21,False,NaN,None,None,connection_error,None
22,True,200.0,https://22uv.org/,text/html; charset=utf-8,None,company_website
23,False,403.0,https://aabelroofing.com/,text/html,http_error,None
24,True,200.0,https://www.polyblast.com/,text/html; charset=UTF-8,None,company_website

In [15]:
reachability_df["accessible"].value_counts()

accessible
True     14
False    11
Name: count, dtype: int64

In [16]:
reachability_df[
    reachability_df["accessible"] == False
][[
    "http_status",
    "content_type",
    "failure_reason"
]]

    http_status content_type    failure_reason
1           NaN         None  connection_error
2           NaN         None  connection_error
3           NaN         None  connection_error
7           NaN         None           timeout
8           NaN         None  connection_error
11          NaN         None  connection_error
13          NaN         None  connection_error
19          NaN         None  connection_error
20          NaN         None  connection_error
21          NaN         None  connection_error
23        403.0    text/html        http_error

In [17]:
sample_2 = pd.concat(
    [sample_2.reset_index(drop=True), reachability_df],
    axis=1
)
sample_2

,name,website,industry,size,type,city,state,country_code,website_normalized,accessible,http_status,final_url,content_type,failure_reason,website_type
0,1ST Choice Energy Services,1stchoiceenergyservices.com,oil and gas,201-500,Public Company,New Philadelphia,Ohio,US,https://1stchoiceenergyservices.com,True,200.0,https://www.heritagecooperative.com/1st-choice...,text/html; charset=utf-8,None,company_website
1,"Academic Research Associates, Inc.",fairygrantmother.com,writing and editing,1-10,Privately Held,Taylor,Texas,US,https://fairygrantmother.com,False,NaN,None,None,connection_error,None
2,247 Dispatching Services,247dispatchingservices.com,truck transportation,1-10,Privately Held,Duluth,Georgia,US,https://247dispatchingservices.com,False,NaN,None,None,connection_error,None
3,8S Solutions LLC,8ssolutionsllc.com,it services and it consulting,11-50,Partnership,Irving,Texas,US,https://8ssolutionsllc.com,False,NaN,None,None,connection_error,None
4,"A&M Tool and Molding Corporation, Inc.",a-mtool.com,mining,1-10,NaN,Arden,North Carolina,US,https://a-mtool.com,True,200.0,http://a-mtool-com.securec95biz.ezhostingserve...,text/html;charset=UTF-8,None,company_website
5,1919 Design Co.,1919designco.com,design services,1-10,Self-Employed,Houston,Texas,US,https://1919designco.com,True,200.0,https://1919designco.com/,text/html,None,company_website
6,"A Network Service, Inc.",anetworkservice.com,computer networking,1-10,Privately Held,Boise,Idaho,US,https://anetworkservice.com,True,200.0,https://anetworkservice.com/,text/html,None,company_website
7,Accurate Upgrades LLC Kitchen & Bathroom Remod...,accurateupgrades.com,construction,1-10,Self-Owned,Salisbury,Maryland,US,https://accurateupgrades.com,False,NaN,None,None,timeout,None
8,Actor Boutique,actorboutique.com,entertainment,1-10,NaN,Atlanta,Georgia,US,https://actorboutique.com,False,NaN,None,None,connection_error,None
9,Able Auto Body,ableautobodysurrey.com,motor vehicle manufacturing,1-10,NaN,New London,Connecticut,US,https://ableautobodysurrey.com,True,200.0,https://ableautobodysurrey.com/,text/html; charset=UTF-8,None,company_website
10,"Acres & Royalty, LLC",acresandroyalty.com,oil and gas,1-10,Privately Held,Ruston,Louisiana,US,https://acresandroyalty.com,True,200.0,https://nlanotary.com/,text/html; charset=utf-8,None,company_website
11,A-Express Towing & Recovery,aexpresstowing.com,truck transportation,1-10,NaN,Palatine,Illinois,US,https://aexpresstowing.com,False,NaN,None,None,connection_error,None
12,Acme Materials,acmebuildingmaterials.com,construction,1-10,NaN,Plano,Texas,US,https://acmebuildingmaterials.com,True,200.0,https://www.qxo.com/welcome-to-beacon,text/html; charset=utf-8,None,company_website
13,Abell Companions Inc,abellcompanions.com,government administration,11-50,NaN,Mc,Texas,US,https://abellcompanions.com,False,NaN,None,None,connection_error,None
14,A Paper Trail,apapertrail.com,accounting,1-10,Self-Owned,Brownsville,Texas,US,https://apapertrail.com,True,200.0,https://apapertrail.com/,text/html; charset=UTF-8,None,company_website
15,A.H. Levy & Co.,ahlevy.com,public policy,1-10,Privately Held,New,York,US,https://ahlevy.com,True,200.0,https://www.ahlevy.com/,text/html;charset=utf-8,None,company_website
16,Accounting Portfolios Inc,pachecotax.com,armed forces,1-10,NaN,Fall River,Massachusetts,US,https://pachecotax.com,True,200.0,https://pachecotax.com/,text/html; charset=UTF-8,None,company_website
17,123 Cash Offer,123cashoffer.com,real estate,1-10,Public Company,Areas,Arizona,US,https://123cashoffer.com,True,200.0,https://123cashoffer.com/,text/html; charset=UTF-8,None,company_website
18,Accio Design LLC,acciodesign.me,design services,1-10,Self-Owned,NaN,NaN,US,https://acciodesign.me,True,200.0,https://www.acciodesign.me/,text/html;charset=utf-8,None,company_website
19,3 Kitchens Catering,3kitchenscatering.com,hospitality,1-10,Self-Owned,Salem,Massachusetts,US,https://3kitchenscatering.com,False,NaN,None,None,connection_error,None
20,Awearness Brand Apparel LLC,110creedapparel.com,retail apparel and fashion,1-10,Self-Employed,Norman,Oklahoma,US,https://110creedapparel.com,False,NaN,None,None,connection_error,None
21,ACPC Health,acpchealth.com,hospitals and health care,1-10,Privately Held,Hoboken,New Jersey,US,https://acpchealth.com,False,NaN,None,None,connection_error,None
22,22 Until Valhalla,22uv.org,armed forces,1-10,Nonprofit,Independence,Kentucky,US,https://22uv.org,True,200.0,https://22uv.org/,text/html; charset=utf-8,None,company_website
23,A Abel Roofing & Siding,aabelroofing.com,construction,1-10,NaN,Dayton,Ohio,US,https://aabelroofing.com,False,403.0,https://aabelroofing.com/,text/html,http_error,None
24,Abrasive Supply Co,polyblast.com,plastics manufacturing,1-10,NaN,Minerva,Ohio,US,https://polyblast.com,True,200.0,https://www.polyblast.com/,text/html; charset=UTF-8,None,company_website

In [18]:
full_pipeline_results = sample_2["website"].apply(validate_website)
full_pipeline_results

0     {'accessible': True, 'http_status': 200, 'fina...
1     {'accessible': False, 'http_status': None, 'fi...
2     {'accessible': False, 'http_status': None, 'fi...
3     {'accessible': False, 'http_status': None, 'fi...
4     {'accessible': True, 'http_status': 200, 'fina...
5     {'accessible': True, 'http_status': 200, 'fina...
6     {'accessible': True, 'http_status': 200, 'fina...
7     {'accessible': False, 'http_status': None, 'fi...
8     {'accessible': False, 'http_status': None, 'fi...
9     {'accessible': True, 'http_status': 200, 'fina...
10    {'accessible': True, 'http_status': 200, 'fina...
11    {'accessible': False, 'http_status': None, 'fi...
12    {'accessible': True, 'http_status': 200, 'fina...
13    {'accessible': False, 'http_status': None, 'fi...
14    {'accessible': True, 'http_status': 200, 'fina...
15    {'accessible': True, 'http_status': 200, 'fina...
16    {'accessible': True, 'http_status': 200, 'fina...
17    {'accessible': True, 'http_status': 200, 'fina...
18    {'accessible': True, 'http_status': 200, 'fina...
19    {'accessible': False, 'http_status': None, 'fi...
20    {'accessible': False, 'http_status': None, 'fi...
21    {'accessible': False, 'http_status': None, 'fi...
22    {'accessible': True, 'http_status': 200, 'fina...
23    {'accessible': False, 'http_status': 403, 'fin...
24    {'accessible': True, 'http_status': 200, 'fina...
Name: website, dtype: object

In [21]:
pd.DataFrame(full_pipeline_results.tolist())

,accessible,http_status,final_url,content_type,failure_reason,website_type
0,True,200.0,https://www.heritagecooperative.com/1st-choice...,text/html; charset=utf-8,None,company_website
1,False,NaN,None,None,connection_error,None
2,False,NaN,None,None,connection_error,None
3,False,NaN,None,None,connection_error,None
4,True,200.0,http://a-mtool-com.securec95biz.ezhostingserve...,text/html;charset=UTF-8,None,company_website
5,True,200.0,https://1919designco.com/,text/html,None,company_website
6,True,200.0,https://anetworkservice.com/,text/html,None,company_website
7,False,NaN,None,None,timeout,None
8,False,NaN,None,None,connection_error,None
9,True,200.0,https://ableautobodysurrey.com/,text/html; charset=UTF-8,None,company_website
10,True,200.0,https://nlanotary.com/,text/html; charset=utf-8,None,company_website
11,False,NaN,None,None,connection_error,None
12,True,200.0,https://www.qxo.com/welcome-to-beacon,text/html; charset=utf-8,None,company_website
13,False,NaN,None,None,connection_error,None
14,True,200.0,https://apapertrail.com/,text/html; charset=UTF-8,None,company_website
15,True,200.0,https://www.ahlevy.com/,text/html;charset=utf-8,None,company_website
16,True,200.0,https://pachecotax.com/,text/html; charset=UTF-8,None,company_website
17,True,200.0,https://123cashoffer.com/,text/html; charset=UTF-8,None,company_website
18,True,200.0,https://www.acciodesign.me/,text/html;charset=utf-8,None,company_website
19,False,NaN,None,None,connection_error,None
20,False,NaN,None,None,connection_error,None
21,False,NaN,None,None,connection_error,None
22,True,200.0,https://22uv.org/,text/html; charset=utf-8,None,company_website
23,False,403.0,https://aabelroofing.com/,text/html,http_error,None
24,True,200.0,https://www.polyblast.com/,text/html; charset=UTF-8,None,company_website

In [23]:
full_pipeline_large_results = sample_1["website"].apply(validate_website)
pd.DataFrame(full_pipeline_large_results.tolist())

,accessible,http_status,final_url,content_type,failure_reason,website_type
0,True,200.0,https://ableautobodysurrey.com/,text/html; charset=UTF-8,None,company_website
1,True,200.0,https://www.coloradoilc.com/,text/html; charset=UTF-8,None,company_website
2,True,200.0,https://www.acmecreditpartners.com/,text/html;charset=utf-8,None,company_website
3,True,200.0,https://www.accudyn.com/,text/html; charset=UTF-8,None,company_website
4,True,200.0,https://www.ahlevy.com/,text/html;charset=utf-8,None,company_website
...,...,...,...,...,...,...
95,False,403.0,https://aaabestwater.com/,text/html,http_error,None
96,False,403.0,https://www.acrosstheboardtherapy.com/,text/html; charset=UTF-8,http_error,None
97,True,200.0,https://www.youtube.com/channel/UCyDPhXWIfJ8ek...,text/html; charset=utf-8,None,company_website
98,False,406.0,https://onepromiseoutpatient.org/,text/html; charset=iso-8859-1,http_error,None
99,False,NaN,None,None,connection_error,None

In [27]:
df_large_results = pd.DataFrame(full_pipeline_large_results.tolist())
pd.set_option('display.max_rows', None)
display(df_large_results)

,accessible,http_status,final_url,content_type,failure_reason,website_type
0,True,200.0,https://ableautobodysurrey.com/,text/html; charset=UTF-8,None,company_website
1,True,200.0,https://www.coloradoilc.com/,text/html; charset=UTF-8,None,company_website
2,True,200.0,https://www.acmecreditpartners.com/,text/html;charset=utf-8,None,company_website
3,True,200.0,https://www.accudyn.com/,text/html; charset=UTF-8,None,company_website
4,True,200.0,https://www.ahlevy.com/,text/html;charset=utf-8,None,company_website
5,True,200.0,https://www.proscale.com/,text/html; charset=UTF-8,None,company_website
6,True,200.0,https://www.accessedboston.com/,text/html;charset=utf-8,None,company_website
7,False,NaN,None,None,connection_error,None
8,False,NaN,None,None,connection_error,None
9,False,NaN,None,None,timeout,None
10,False,NaN,None,None,connection_error,None
11,True,200.0,https://1strive.com/,text/html; charset=UTF-8,None,company_website
12,True,200.0,https://www.acciodesign.me/,text/html;charset=utf-8,None,company_website
13,False,NaN,None,None,connection_error,None
14,True,200.0,https://www.adrenalingaming.com/,text/html; charset=UTF-8,None,company_website
15,False,NaN,None,None,connection_error,None
16,False,NaN,None,None,connection_error,None
17,True,200.0,https://adducates.com/,text/html; charset=UTF-8,None,company_website
18,True,200.0,https://nlanotary.com/,text/html; charset=utf-8,None,company_website
19,True,200.0,https://www.abareaffair.com/,text/html,None,company_website
20,True,200.0,https://www.absencestudio.com/,text/html;charset=utf-8,None,company_website
21,True,200.0,https://www.3dves.com,text/html,None,company_website
22,True,200.0,https://anetworkservice.com/,text/html,None,company_website
23,True,200.0,https://ableensemble.com/,text/html; charset=UTF-8,None,company_website
24,True,200.0,https://www.48fineart.com/,text/html; charset=UTF-8,None,company_website
25,False,NaN,None,None,connection_error,None
26,True,200.0,https://22uv.org/,text/html; charset=utf-8,None,company_website
27,True,200.0,https://www.southloopchiropractor.com/,text/html; charset=utf-8,None,company_website
28,True,200.0,https://adivi.com/,text/html; charset=utf-8,None,company_website
29,False,NaN,None,None,connection_error,None
30,False,NaN,None,None,connection_error,None
31,False,NaN,None,None,connection_error,None
32,False,502.0,https://allaccessautomotive.com/,text/html; charset=UTF-8,http_error,None
33,False,NaN,None,None,connection_error,None
34,False,404.0,https://flutterbyearomatics.com/eo.html,text/html,http_error,None
35,True,200.0,https://410labs.com/,text/html,None,company_website
36,False,403.0,https://acdcargo.com/,text/html,http_error,None
37,True,200.0,https://academyzen.com/,text/html; charset=UTF-8,None,company_website
38,False,NaN,None,None,connection_error,None
39,True,200.0,https://1919designco.com/,text/html,None,company_website
40,True,200.0,https://boe-companies.com/,text/html,None,company_website
41,False,NaN,None,None,connection_error,None
42,False,403.0,https://aabelroofing.com/,text/html,http_error,None
43,True,200.0,https://skintherapy.com/,text/html; charset=UTF-8,None,company_website
44,True,200.0,http://a-mtool-com.securec95biz.ezhostingserve...,text/html;charset=UTF-8,None,company_website
45,False,NaN,None,None,connection_error,None
46,True,200.0,https://www.tumblr.com/,text/html; charset=utf-8,None,company_website
47,True,200.0,https://accedemold.com/,text/html; charset=UTF-8,None,company_website
48,False,NaN,None,None,connection_error,None
49,False,404.0,https://adrevenuesolutions.com/,text/html; charset=utf-8,http_error,None
50,True,200.0,https://abussuan.com/,text/html,None,company_website
51,False,NaN,None,None,connection_error,None
52,False,NaN,None,None,connection_error,None
53,False,NaN,None,None,connection_error,None
54,False,NaN,None,None,connection_error,None
55,False,NaN,None,None,connection_error,None
56,True,200.0,https://accentedge.org/,text/html; charset=UTF-8,None,company_website
57,False,NaN,None,None,connection_error,None
58,True,200.0,https://4otf.com/,text/html; charset=UTF-8,None,company_website
59,False,NaN,None,None,connection_error,None
60,False,NaN,None,None,connection_error,None
61,True,200.0,https://180dc.org/,text/html; charset=utf-8,None,company_website
62,False,NaN,None,None,connection_error,None
63,True,200.0,https://www.47and10.com/,text/html;charset=utf-8,None,company_website
64,False,NaN,None,None,timeout,None
65,True,200.0,https://aceexpresscoaches.com/,text/html; charset=UTF-8,None,company_website
66,True,200.0,https://accuformprint.com/,text/html; charset=UTF-8,None,company_website
67,False,NaN,None,None,connection_error,None
68,True,200.0,https://1stchoicesecuritysolutions.com/,text/html;charset=utf-8,None,company_website
69,True,200.0,https://www.polyblast.com/,text/html; charset=UTF-8,None,company_website
70,False,NaN,None,None,connection_error,None
71,False,NaN,None,None,connection_error,None
72,False,403.0,https://acadianhba.com/,text/html,http_error,None
73,True,200.0,https://www.qxo.com/welcome-to-beacon,text/html; charset=utf-8,None,company_website
74,False,NaN,None,None,connection_error,None
75,True,200.0,https://973thedawg.com/,text/html; charset=utf-8,None,company_website
76,True,200.0,https://pachecotax.com/,text/html; charset=UTF-8,None,company_website
77,True,200.0,https://123cashoffer.com/,text/html; charset=UTF-8,None,company_website
78,False,NaN,None,None,connection_error,None
79,False,NaN,None,None,connection_error,None
80,False,NaN,None,None,timeout,None
81,True,200.0,https://1secureaudit.com/,text/html,None,company_website
82,True,200.0,https://8aspects.com/,text/html,None,company_website
83,True,200.0,https://www.heritagecooperative.com/1st-choice...,text/html; charset=utf-8,None,company_website
84,True,200.0,https://www.abpackaging.com/,text/html; charset=utf-8,None,company_website
85,True,200.0,https://www.absarokaenergy.com/,text/html;charset=utf-8,None,company_website
86,True,200.0,https://www.amswebdesign.com/,text/html; charset=UTF-8,None,company_website
87,False,403.0,https://marriott.com/,text/html,http_error,None
88,False,NaN,None,None,connection_error,None
89,True,200.0,https://abetterwaytms.com/,text/html; charset=UTF-8,None,company_website
90,True,200.0,https://apapertrail.com/,text/html; charset=UTF-8,None,company_website
91,False,403.0,https://aandbaccessories.com/,text/html,http_error,None
92,False,403.0,https://ableelectropolishing.com/,text/html,http_error,None
93,True,200.0,https://www.instagram.com/,"text/html; charset=""utf-8""",None,company_website
94,True,200.0,https://www.actiontankusa.org/,text/html,None,company_website
95,False,403.0,https://aaabestwater.com/,text/html,http_error,None
96,False,403.0,https://www.acrosstheboardtherapy.com/,text/html; charset=UTF-8,http_error,None
97,True,200.0,https://www.youtube.com/channel/UCyDPhXWIfJ8ek...,text/html; charset=utf-8,None,company_website
98,False,406.0,https://onepromiseoutpatient.org/,text/html; charset=iso-8859-1,http_error,None
99,False,NaN,None,None,connection_error,None

In [28]:
df_large_results["accessible"].value_counts()

accessible
True     53
False    47
Name: count, dtype: int64

In [29]:
df_large_results["failure_reason"].value_counts()

failure_reason
connection_error    32
http_error          12
timeout              3
Name: count, dtype: int64

In [30]:
df_large_results[df_large_results["accessible"] == True]

,accessible,http_status,final_url,content_type,failure_reason,website_type
0,True,200.0,https://ableautobodysurrey.com/,text/html; charset=UTF-8,None,company_website
1,True,200.0,https://www.coloradoilc.com/,text/html; charset=UTF-8,None,company_website
2,True,200.0,https://www.acmecreditpartners.com/,text/html;charset=utf-8,None,company_website
3,True,200.0,https://www.accudyn.com/,text/html; charset=UTF-8,None,company_website
4,True,200.0,https://www.ahlevy.com/,text/html;charset=utf-8,None,company_website
5,True,200.0,https://www.proscale.com/,text/html; charset=UTF-8,None,company_website
6,True,200.0,https://www.accessedboston.com/,text/html;charset=utf-8,None,company_website
11,True,200.0,https://1strive.com/,text/html; charset=UTF-8,None,company_website
12,True,200.0,https://www.acciodesign.me/,text/html;charset=utf-8,None,company_website
14,True,200.0,https://www.adrenalingaming.com/,text/html; charset=UTF-8,None,company_website
17,True,200.0,https://adducates.com/,text/html; charset=UTF-8,None,company_website
18,True,200.0,https://nlanotary.com/,text/html; charset=utf-8,None,company_website
19,True,200.0,https://www.abareaffair.com/,text/html,None,company_website
20,True,200.0,https://www.absencestudio.com/,text/html;charset=utf-8,None,company_website
21,True,200.0,https://www.3dves.com,text/html,None,company_website
22,True,200.0,https://anetworkservice.com/,text/html,None,company_website
23,True,200.0,https://ableensemble.com/,text/html; charset=UTF-8,None,company_website
24,True,200.0,https://www.48fineart.com/,text/html; charset=UTF-8,None,company_website
26,True,200.0,https://22uv.org/,text/html; charset=utf-8,None,company_website
27,True,200.0,https://www.southloopchiropractor.com/,text/html; charset=utf-8,None,company_website
28,True,200.0,https://adivi.com/,text/html; charset=utf-8,None,company_website
35,True,200.0,https://410labs.com/,text/html,None,company_website
37,True,200.0,https://academyzen.com/,text/html; charset=UTF-8,None,company_website
39,True,200.0,https://1919designco.com/,text/html,None,company_website
40,True,200.0,https://boe-companies.com/,text/html,None,company_website
43,True,200.0,https://skintherapy.com/,text/html; charset=UTF-8,None,company_website
44,True,200.0,http://a-mtool-com.securec95biz.ezhostingserve...,text/html;charset=UTF-8,None,company_website
46,True,200.0,https://www.tumblr.com/,text/html; charset=utf-8,None,company_website
47,True,200.0,https://accedemold.com/,text/html; charset=UTF-8,None,company_website
50,True,200.0,https://abussuan.com/,text/html,None,company_website
56,True,200.0,https://accentedge.org/,text/html; charset=UTF-8,None,company_website
58,True,200.0,https://4otf.com/,text/html; charset=UTF-8,None,company_website
61,True,200.0,https://180dc.org/,text/html; charset=utf-8,None,company_website
63,True,200.0,https://www.47and10.com/,text/html;charset=utf-8,None,company_website
65,True,200.0,https://aceexpresscoaches.com/,text/html; charset=UTF-8,None,company_website
66,True,200.0,https://accuformprint.com/,text/html; charset=UTF-8,None,company_website
68,True,200.0,https://1stchoicesecuritysolutions.com/,text/html;charset=utf-8,None,company_website
69,True,200.0,https://www.polyblast.com/,text/html; charset=UTF-8,None,company_website
73,True,200.0,https://www.qxo.com/welcome-to-beacon,text/html; charset=utf-8,None,company_website
75,True,200.0,https://973thedawg.com/,text/html; charset=utf-8,None,company_website
76,True,200.0,https://pachecotax.com/,text/html; charset=UTF-8,None,company_website
77,True,200.0,https://123cashoffer.com/,text/html; charset=UTF-8,None,company_website
81,True,200.0,https://1secureaudit.com/,text/html,None,company_website
82,True,200.0,https://8aspects.com/,text/html,None,company_website
83,True,200.0,https://www.heritagecooperative.com/1st-choice...,text/html; charset=utf-8,None,company_website
84,True,200.0,https://www.abpackaging.com/,text/html; charset=utf-8,None,company_website
85,True,200.0,https://www.absarokaenergy.com/,text/html;charset=utf-8,None,company_website
86,True,200.0,https://www.amswebdesign.com/,text/html; charset=UTF-8,None,company_website
89,True,200.0,https://abetterwaytms.com/,text/html; charset=UTF-8,None,company_website
90,True,200.0,https://apapertrail.com/,text/html; charset=UTF-8,None,company_website
93,True,200.0,https://www.instagram.com/,"text/html; charset=""utf-8""",None,company_website
94,True,200.0,https://www.actiontankusa.org/,text/html,None,company_website
97,True,200.0,https://www.youtube.com/channel/UCyDPhXWIfJ8ek...,text/html; charset=utf-8,None,company_website

URLs resolving to known social media, directory, URL-shortening, parked, or domain-for-sale pages were excluded. Remaining accessible HTML pages were treated as company websites.