In [15]:
import pandas as pd

In [4]:
us_companies = pd.read_csv("../data/processed/us_companies.csv")
us_companies.head()

,name,website,industry,size,type,city,state,country_code
0,~ Fathom ~ Computer and Networking Services,fathomcomputerservices.com,information technology & services,1-10,Self-Owned,Lowell,Massachusetts,US
1,♞ knight's path,knightspath.com,computer games,1-10,Privately Held,Laguna Beach,California,US
2,Ebisu's Bay,ebisusbay.com,blockchain services,11-50,Privately Held,Lawrence,Kansas,US
3,0y1 Jewelry Studio,0y1jewelrystudio.com,retail apparel and fashion,1-10,Self-Employed,New,York,US
4,"1-14 CAV, 3-2 Stryker BDE, US Army",wikipedia.org,armed forces,1K-5K,Government Agency,Lewis-Mcchord,Washington,US

In [16]:
mapping = pd.read_csv("../data/reference/industry_mapping.csv")
mapping.head()

,industry,company_count,industry_group,review_status
0,construction,168206,Construction & Real Estate,reviewed
1,advertising services,124391,Marketing & Communications,reviewed
2,real estate,119215,Construction & Real Estate,reviewed
3,it services and it consulting,93718,Technology & Digital,reviewed
4,hospitals and health care,89602,Healthcare,reviewed

In [17]:
merged = us_companies.merge(
    mapping[["industry", "industry_group"]],
    on="industry",
    how="left"    
)

In [18]:
merged.head()

,name,website,industry,size,type,city,state,country_code,industry_group
0,~ Fathom ~ Computer and Networking Services,fathomcomputerservices.com,information technology & services,1-10,Self-Owned,Lowell,Massachusetts,US,Technology & Digital
1,♞ knight's path,knightspath.com,computer games,1-10,Privately Held,Laguna Beach,California,US,Technology & Digital
2,Ebisu's Bay,ebisusbay.com,blockchain services,11-50,Privately Held,Lawrence,Kansas,US,NaN
3,0y1 Jewelry Studio,0y1jewelrystudio.com,retail apparel and fashion,1-10,Self-Employed,New,York,US,Commerce & Consumer
4,"1-14 CAV, 3-2 Stryker BDE, US Army",wikipedia.org,armed forces,1K-5K,Government Agency,Lewis-Mcchord,Washington,US,Government & Public Affairs

In [19]:
merged["industry_group"].isna().sum()

np.int64(59800)

In [20]:
merged["industry_group"].value_counts()

industry_group
Construction & Real Estate       339313
Legal & Professional Services    302504
Technology & Digital             295647
Manufacturing & Industrial       239848
Commerce & Consumer              231277
Healthcare                       217065
Nonprofit & Social Services      182758
Finance & Insurance              178408
Hospitality & Travel             160538
Marketing & Communications       154752
Education                        154669
Arts & Design                    122767
Media & Publishing                96750
Fitness & Wellness                88651
Entertainment & Recreation        85150
Energy & Environment              75993
Transportation & Logistics        58972
Government & Public Affairs       49704
Agriculture & Food                44785
Technology & Information           7258
Art & Design                       6399
Ambiguous                          5672
Name: count, dtype: int64

In [21]:
mapping["industry_group"].value_counts()

industry_group
Manufacturing & Industrial       26
Commerce & Consumer              21
Legal & Professional Services    19
Technology & Digital             13
Healthcare                       11
Arts & Design                    11
Government & Public Affairs      10
Media & Publishing                9
Transportation & Logistics        9
Construction & Real Estate        8
Finance & Insurance               8
Nonprofit & Social Services       8
Education                         8
Hospitality & Travel              7
Energy & Environment              7
Agriculture & Food                7
Entertainment & Recreation        6
Marketing & Communications        3
Fitness & Wellness                2
Art & Design                      2
Technology & Information          1
Ambiguous                         1
Name: count, dtype: int64

In [28]:
len(merged)

3158680

In [23]:
nan_removed = merged[merged["industry_group"].notna()]
sample_population = nan_removed[nan_removed["industry_group"] != "Ambiguous"]
sample_population

,name,website,industry,size,type,city,state,country_code,industry_group
0,~ Fathom ~ Computer and Networking Services,fathomcomputerservices.com,information technology & services,1-10,Self-Owned,Lowell,Massachusetts,US,Technology & Digital
1,♞ knight's path,knightspath.com,computer games,1-10,Privately Held,Laguna Beach,California,US,Technology & Digital
3,0y1 Jewelry Studio,0y1jewelrystudio.com,retail apparel and fashion,1-10,Self-Employed,New,York,US,Commerce & Consumer
4,"1-14 CAV, 3-2 Stryker BDE, US Army",wikipedia.org,armed forces,1K-5K,Government Agency,Lewis-Mcchord,Washington,US,Government & Public Affairs
5,1-800-Biz-Broker | Business Broker in Riversid...,justsoldbiz.com,real estate,1-10,Privately Held,Riverside,California,US,Construction & Real Estate
...,...,...,...,...,...,...,...,...,...
3158675,UNR Civil and Environmental Engineering,unr.edu,civil engineering,11-50,Educational,Reno,Nevada,US,Construction & Real Estate
3158676,Victor School,victorschools.org,higher education,1-10,NaN,Acton,Massachusetts,US,Education
3158677,Virginia Highlands Community College,vhcc.edu,higher education,51-200,Educational,Abingdon,Virginia,US,Education
3158678,Watauga High School,watauga.k12.nc.us,primary and secondary education,51-200,NaN,Boone,North Carolina,US,Education
3158679,Westmont College,westmont.edu,higher education,201-500,Educational,Santa Barbara,California,US,Education

In [24]:
sample_population["industry_group"].value_counts()

industry_group
Construction & Real Estate       339313
Legal & Professional Services    302504
Technology & Digital             295647
Manufacturing & Industrial       239848
Commerce & Consumer              231277
Healthcare                       217065
Nonprofit & Social Services      182758
Finance & Insurance              178408
Hospitality & Travel             160538
Marketing & Communications       154752
Education                        154669
Arts & Design                    122767
Media & Publishing                96750
Fitness & Wellness                88651
Entertainment & Recreation        85150
Energy & Environment              75993
Transportation & Logistics        58972
Government & Public Affairs       49704
Agriculture & Food                44785
Technology & Information           7258
Art & Design                       6399
Name: count, dtype: int64

In [29]:
len(sample_population)

3093208

In [30]:
sample_population["industry_group"].isna().sum()

np.int64(0)

In [31]:
sample_population.to_csv(
    "../data/processed/sampling_population.csv",
    index=False
)

Created sampling_population.csv - US-only company data with companies from the top 19 industry groups; filtered out industries classified as Ambiguous