In [1]:
import asyncio
import pandas as pd

import sys
sys.path.append("..")

from src.url_validator import validate_website
from src.typography_scraper import load_page

In [2]:
df = pd.read_csv("../data/processed/sampling_population.csv")
df

,name,website,industry,size,type,city,state,country_code,industry_group
0,~ Fathom ~ Computer and Networking Services,fathomcomputerservices.com,information technology & services,1-10,Self-Owned,Lowell,Massachusetts,US,Technology & Digital
1,♞ knight's path,knightspath.com,computer games,1-10,Privately Held,Laguna Beach,California,US,Technology & Digital
2,0y1 Jewelry Studio,0y1jewelrystudio.com,retail apparel and fashion,1-10,Self-Employed,New,York,US,Commerce & Consumer
3,"1-14 CAV, 3-2 Stryker BDE, US Army",wikipedia.org,armed forces,1K-5K,Government Agency,Lewis-Mcchord,Washington,US,Government & Public Affairs
4,1-800-Biz-Broker | Business Broker in Riversid...,justsoldbiz.com,real estate,1-10,Privately Held,Riverside,California,US,Construction & Real Estate
...,...,...,...,...,...,...,...,...,...
3093203,UNR Civil and Environmental Engineering,unr.edu,civil engineering,11-50,Educational,Reno,Nevada,US,Construction & Real Estate
3093204,Victor School,victorschools.org,higher education,1-10,NaN,Acton,Massachusetts,US,Education
3093205,Virginia Highlands Community College,vhcc.edu,higher education,51-200,Educational,Abingdon,Virginia,US,Education
3093206,Watauga High School,watauga.k12.nc.us,primary and secondary education,51-200,NaN,Boone,North Carolina,US,Education
3093207,Westmont College,westmont.edu,higher education,201-500,Educational,Santa Barbara,California,US,Education

In [3]:
sample = df.sample(40, random_state=42)
sample

,name,website,industry,size,type,city,state,country_code,industry_group
134900,Nigerian Visa & Travel Services,nigerianvisaservices.com,travel arrangements,1-10,Public Company,Houston,Texas,US,Hospitality & Travel
90594,HUSL Digital,husldigital.com,advertising services,11-50,Privately Held,Reston,Virginia,US,Marketing & Communications
1590181,The Bait Shoppe,baitshoppe.com,advertising services,11-50,Privately Held,New York,New York,US,Marketing & Communications
1565349,"Cobalt Sales Management, LLC",cobaltsalesmgt.com,professional training and coaching,1-10,Self-Owned,Tampa,Florida,US,Education
2493185,Med Rank Interactive,medrankinteractive.com,advertising services,1-10,Privately Held,Fort Mill,South Carolina,US,Marketing & Communications
1506761,New Style Motherlode Studio,newstylemotherlode.com,entertainment providers,11-50,NaN,Oakland,California,US,Entertainment & Recreation
680665,Global Fashion Exchange (GFX),globalfashionxchange.org,apparel & fashion,1-10,Partnership,New York,New York,US,Commerce & Consumer
1795787,"Heckscher, Teillon, Terrill & Sager, P.C.",htts.com,law practice,11-50,Privately Held,West Conshohocken,Pennsylvania,US,Legal & Professional Services
2968717,"Write for Me, LLC",writeformellc.com,writing and editing,1-10,Self-Owned,Hammond,Wisconsin,US,Media & Publishing
2619685,MJO Bookkeeper,mjobookkeeper.com,accounting,1-10,Self-Employed,Audubon,Pennsylvania,US,Legal & Professional Services
464143,Kirschner Contractors,kirschnercontractors.com,construction,1-10,Partnership,Kailua,Hawaii,US,Construction & Real Estate
1084064,Dale Feste Automotive,dalefesteautomotive.com,automotive,11-50,NaN,Hopkins,Minnesota,US,Manufacturing & Industrial
1594779,YQ Art,yqart.com,design services,11-50,Privately Held,Riffa,NaN,US,Arts & Design
106208,Swift Prepaid Solutions,swiftprepaid.com,financial services,51-200,Privately Held,Buffalo Grove,Illinois,US,Finance & Insurance
366165,Table Bay Financial,tablebayfinancial.com,insurance,11-50,NaN,Torrance,California,US,Finance & Insurance
301089,Bay Area Crane Service Inc,bayareacrane.com,industrial machinery manufacturing,1-10,NaN,Houston,Texas,US,Manufacturing & Industrial
2064638,Nuestra Visión,nuestravision.tv,broadcast media production and distribution,51-200,Public Company,Miami,Florida,US,Media & Publishing
1627023,Taubman Center for State & Local Government,harvard.edu,higher education,11-50,Educational,Cambridge,Massachusetts,US,Education
1844161,Prompt Digital,promptdigital.io,"technology, information and internet",1-10,Privately Held,San Francisco,California,US,Technology & Digital
1609076,Gordon Property Management,gpmsf.com,real estate,1-10,Privately Held,San Francisco,California,US,Construction & Real Estate
2352265,Grette Associates LLC,gretteassociates.com,environmental services,11-50,Partnership,Wenatchee,Washington,US,Energy & Environment
2529086,"Business Data Applications, Inc.",healthycontracts.com,it services and it consulting,11-50,Privately Held,Exeter,New Hampshire,US,Technology & Digital
3015122,Customs & Classics Auto World,customsandclassicsautoworld.com,motor vehicle manufacturing,1-10,Public Company,Otsego,Minnesota,US,Manufacturing & Industrial
1266487,Care Net Pregnancy Center of Frederick,carenetfrederick.org,medical practices,11-50,NaN,Frederick,Maryland,US,Healthcare
1663120,St. Plant,stplant.co,retail,1-10,Privately Held,Washington,District Of Columbia,US,Commerce & Consumer
1056473,Kwfc Radio,kwfc.org,graphic design,1-10,NaN,Springfield,Missouri,US,Arts & Design
487895,BridgeSocial,bridgesocialmedia.com,advertising services,1-10,Privately Held,Seattle,Washington,US,Marketing & Communications
1427275,Katherine Johnson Law LLC,katherinejohnsonlaw.com,law practice,1-10,Privately Held,Chicago,Illinois,US,Legal & Professional Services
2317456,INKollective,inkollective.com,apparel & fashion,1-10,Privately Held,Rolla,Missouri,US,Commerce & Consumer
2590211,Sheriff Plumbing,sheriffplumbing.com,building materials,1-10,NaN,Rancho Cucamonga,California,US,Construction & Real Estate
1849855,Team BRIDGES,bridgesusa.org,education administration programs,11-50,Nonprofit,Memphis,Tennessee,US,Education
1648896,"Incite Strategic Partners, LLC",incitesp.com,hospitals and health care,11-50,Partnership,Lake Oswego,Oregon,US,Healthcare
2547470,OMAX Oral & Maxillofacial Surgery,omaxsurgery.com,hospitals and health care,11-50,Privately Held,Spokane Valley,Washington,US,Healthcare
332490,"Vex Intel, LLC",archive.org,security and investigations,1-10,Privately Held,Tampa,Florida,US,Legal & Professional Services
1358179,Noe Import Auto,noeimports.com,food and beverage services,1-10,NaN,Mesa,Arizona,US,Hospitality & Travel
737852,Traverse Anesthesia Assoc P C,taapc.org,medical practices,11-50,NaN,Traverse City,Michigan,US,Healthcare
1134011,Miracle Ear Hearing Centers,miraclear.com,hospitals and health care,11-50,Public Company,Janesville,Wisconsin,US,Healthcare
213333,Riffle Contracting,rifflecontracting.com,construction,1-10,NaN,Hurst,Texas,US,Construction & Real Estate
1989424,Nevada Linen Supply,nevadalinen.com,hospitality,51-200,Privately Held,Las Vegas,Nevada,US,Hospitality & Travel
1166983,"Just Books Publishing, L.L.C",justbookspublishing.com,book and periodical publishing,1-10,Public Company,Zephyrhills,Florida,US,Media & Publishing

In [4]:
url_access = sample["website"].apply(validate_website)
access_results = pd.DataFrame(url_access.tolist())

In [10]:
access_results

,accessible,http_status,final_url,content_type,failure_reason,website_type
0,True,200.0,https://nigerianvisaservices.com/,text/html,NaN,company_website
1,True,200.0,https://husldigital.com/,text/html; charset=UTF-8,NaN,company_website
2,True,200.0,https://baitshoppe.com/,text/html; charset=UTF-8,NaN,company_website
3,False,NaN,NaN,NaN,connection_error,NaN
4,True,200.0,https://medrankinteractive.com/,text/html; charset=UTF-8,NaN,company_website
5,True,200.0,https://www.newstylemotherlode.com/,text/html; charset=UTF-8,NaN,company_website
6,True,200.0,https://www.globalfashionxchange.org/,text/html; charset=UTF-8,NaN,company_website
7,True,200.0,https://www.htts.com/,text/html; charset=UTF-8,NaN,company_website
8,False,NaN,NaN,NaN,connection_error,NaN
9,True,200.0,https://mjobookkeeper.com/,text/html,NaN,company_website
10,True,200.0,https://kirschnercontractors.com/,text/html; charset=UTF-8,NaN,company_website
11,True,200.0,https://www.dalefesteautomotive.com/,text/html; charset=UTF-8,NaN,company_website
12,False,NaN,NaN,NaN,connection_error,NaN
13,False,NaN,NaN,NaN,connection_error,NaN
14,False,NaN,NaN,NaN,connection_error,NaN
15,False,NaN,NaN,NaN,connection_error,NaN
16,False,403.0,https://nuestravision.tv/,text/html,http_error,NaN
17,True,200.0,https://www.harvard.edu/,text/html; charset=UTF-8,NaN,company_website
18,True,200.0,https://www.qontour.com/,text/html; charset=utf-8,NaN,company_website
19,True,200.0,https://gpmsf.com/,text/html; charset=UTF-8,NaN,company_website
20,False,403.0,https://gretteassociates.com/,text/html; charset=iso-8859-1,http_error,NaN
21,True,200.0,https://www.healthycontracts.com/,text/html; charset=UTF-8,NaN,company_website
22,False,NaN,NaN,NaN,connection_error,NaN
23,False,403.0,https://carenetfrederick.org/,text/html,http_error,NaN
24,False,404.0,https://www.stplant.co/,text/html;charset=utf-8,http_error,NaN
25,True,200.0,https://kwfc.org/,text/html; charset=UTF-8,NaN,company_website
26,True,200.0,https://bridgesocialmedia.com/,text/html; charset=utf-8,NaN,company_website
27,True,200.0,https://katherinejohnsonlaw.com/,text/html,NaN,company_website
28,True,200.0,https://www.inkollective.com/,text/html; charset=UTF-8,NaN,company_website
29,False,NaN,NaN,NaN,connection_error,NaN
30,True,200.0,https://bridgesusa.org/,text/html; charset=utf-8,NaN,company_website
31,True,200.0,https://incitesp.com/,text/html; charset=UTF-8,NaN,company_website
32,True,200.0,https://www.omaxsurgery.com/,text/html; charset=utf-8,NaN,company_website
33,True,200.0,https://archive.org/,text/html; charset=utf-8,NaN,company_website
34,True,200.0,https://noeimports.com/,text/html; charset=UTF-8,NaN,company_website
35,True,200.0,https://taapc.org/en,text/html; charset=utf-8,NaN,company_website
36,False,465.0,http://www.dynamo.com/assets.htm,text/html; charset=utf-8,http_error,NaN
37,True,200.0,https://www.rifflecontracting.com/,text/html; charset=UTF-8,NaN,company_website
38,False,403.0,https://www.imagefirst.com/nevada-linen-supply/,text/html,http_error,NaN
39,False,NaN,NaN,NaN,connection_error,NaN

In [5]:
success = access_results[access_results["website_type"] == "company_website"]
success

,accessible,http_status,final_url,content_type,failure_reason,website_type
0,True,200.0,https://nigerianvisaservices.com/,text/html,NaN,company_website
1,True,200.0,https://husldigital.com/,text/html; charset=UTF-8,NaN,company_website
2,True,200.0,https://baitshoppe.com/,text/html; charset=UTF-8,NaN,company_website
4,True,200.0,https://medrankinteractive.com/,text/html; charset=UTF-8,NaN,company_website
5,True,200.0,https://www.newstylemotherlode.com/,text/html; charset=UTF-8,NaN,company_website
6,True,200.0,https://www.globalfashionxchange.org/,text/html; charset=UTF-8,NaN,company_website
7,True,200.0,https://www.htts.com/,text/html; charset=UTF-8,NaN,company_website
9,True,200.0,https://mjobookkeeper.com/,text/html,NaN,company_website
10,True,200.0,https://kirschnercontractors.com/,text/html; charset=UTF-8,NaN,company_website
11,True,200.0,https://www.dalefesteautomotive.com/,text/html; charset=UTF-8,NaN,company_website
17,True,200.0,https://www.harvard.edu/,text/html; charset=UTF-8,NaN,company_website
18,True,200.0,https://www.qontour.com/,text/html; charset=utf-8,NaN,company_website
19,True,200.0,https://gpmsf.com/,text/html; charset=UTF-8,NaN,company_website
21,True,200.0,https://www.healthycontracts.com/,text/html; charset=UTF-8,NaN,company_website
25,True,200.0,https://kwfc.org/,text/html; charset=UTF-8,NaN,company_website
26,True,200.0,https://bridgesocialmedia.com/,text/html; charset=utf-8,NaN,company_website
27,True,200.0,https://katherinejohnsonlaw.com/,text/html,NaN,company_website
28,True,200.0,https://www.inkollective.com/,text/html; charset=UTF-8,NaN,company_website
30,True,200.0,https://bridgesusa.org/,text/html; charset=utf-8,NaN,company_website
31,True,200.0,https://incitesp.com/,text/html; charset=UTF-8,NaN,company_website
32,True,200.0,https://www.omaxsurgery.com/,text/html; charset=utf-8,NaN,company_website
33,True,200.0,https://archive.org/,text/html; charset=utf-8,NaN,company_website
34,True,200.0,https://noeimports.com/,text/html; charset=UTF-8,NaN,company_website
35,True,200.0,https://taapc.org/en,text/html; charset=utf-8,NaN,company_website
37,True,200.0,https://www.rifflecontracting.com/,text/html; charset=UTF-8,NaN,company_website

In [6]:
len(success)

25

In [7]:
typography_results = await load_page(success["final_url"].iloc[0])

typography_results

{'url': 'https://nigerianvisaservices.com/',
 'font_family': None,
 'font_size': None,
 'font_weight': None,
 'line_height': None,
 'scrape_status': 'failed',
 'failure_reason': 'no_h1'}

In [8]:
urls = success["final_url"].tolist()

typography_results_all = await asyncio.gather(
    *(load_page(url) for url in urls)
)

typography_results_all

[{'url': 'https://nigerianvisaservices.com/',
  'font_family': None,
  'font_size': None,
  'font_weight': None,
  'line_height': None,
  'scrape_status': 'failed',
  'failure_reason': 'no_h1'},
 {'url': 'https://husldigital.com/',
  'font_family': 'ff-good-web-pro, sans-serif',
  'font_size': '60px',
  'font_weight': '700',
  'line_height': '72px',
  'scrape_status': 'success',
  'failure_reason': None},
 {'url': 'https://baitshoppe.com/',
  'font_family': 'Outfit, sans-serif',
  'font_size': '90px',
  'font_weight': '400',
  'line_height': '99px',
  'scrape_status': 'success',
  'failure_reason': None},
 {'url': 'https://medrankinteractive.com/',
  'font_family': 'Poppins',
  'font_size': '24px',
  'font_weight': '700',
  'line_height': '48px',
  'scrape_status': 'success',
  'failure_reason': None},
 {'url': 'https://www.newstylemotherlode.com/',
  'font_family': 'didot-w01-italic, serif',
  'font_size': '40px',
  'font_weight': '400',
  'line_height': '40px',
  'scrape_status': 'success',
  'failure_reason': None},
 {'url': 'https://www.globalfashionxchange.org/',
  'font_family': '"libre baskerville", serif',
  'font_size': '22px',
  'font_weight': '400',
  'line_height': 'normal',
  'scrape_status': 'success',
  'failure_reason': None},
 {'url': 'https://www.htts.com/',
  'font_family': 'Cormorant, sans-serif',
  'font_size': '65px',
  'font_weight': '500',
  'line_height': '69px',
  'scrape_status': 'success',
  'failure_reason': None},
 {'url': 'https://mjobookkeeper.com/',
  'font_family': None,
  'font_size': None,
  'font_weight': None,
  'line_height': None,
  'scrape_status': 'failed',
  'failure_reason': 'no_h1'},
 {'url': 'https://kirschnercontractors.com/',
  'font_family': '"Bakbak One", sans-serif',
  'font_size': '45px',
  'font_weight': '700',
  'line_height': 'normal',
  'scrape_status': 'success',
  'failure_reason': None},
 {'url': 'https://www.dalefesteautomotive.com/',
  'font_family': 'Arial, Helvetica, Arial, Lucida, sans-serif',
  'font_size': '30px',
  'font_weight': '500',
  'line_height': '30px',
  'scrape_status': 'success',
  'failure_reason': None},
 {'url': 'https://www.harvard.edu/',
  'font_family': '"GT America Standard Regular"',
  'font_size': '36px',
  'font_weight': '400',
  'line_height': '54px',
  'scrape_status': 'success',
  'failure_reason': None},
 {'url': 'https://www.qontour.com/',
  'font_family': '"Funnel Display", sans-serif',
  'font_size': '94.08px',
  'font_weight': '400',
  'line_height': '94.08px',
  'scrape_status': 'success',
  'failure_reason': None},
 {'url': 'https://gpmsf.com/',
  'font_family': '"Playfair Display", Georgia, "Times New Roman", serif',
  'font_size': '72px',
  'font_weight': '500',
  'line_height': '93.6px',
  'scrape_status': 'success',
  'failure_reason': None},
 {'url': 'https://www.healthycontracts.com/',
  'font_family': 'spinnaker, sans-serif',
  'font_size': '40px',
  'font_weight': '400',
  'line_height': 'normal',
  'scrape_status': 'success',
  'failure_reason': None},
 {'url': 'https://kwfc.org/',
  'font_family': None,
  'font_size': None,
  'font_weight': None,
  'line_height': None,
  'scrape_status': 'failed',
  'failure_reason': 'no_h1'},
 {'url': 'https://bridgesocialmedia.com/',
  'font_family': '"Microsoft YaHei", "PingFang SC", sans-serif',
  'font_size': '38px',
  'font_weight': '700',
  'line_height': 'normal',
  'scrape_status': 'success',
  'failure_reason': None},
 {'url': 'https://katherinejohnsonlaw.com/',
  'font_family': None,
  'font_size': None,
  'font_weight': None,
  'line_height': None,
  'scrape_status': 'failed',
  'failure_reason': 'no_h1'},
 {'url': 'https://www.inkollective.com/',
  'font_family': None,
  'font_size': None,
  'font_weight': None,
  'line_height': None,
  'scrape_status': 'failed',
  'failure_reason': 'no_h1'},
 {'url': 'https://bridgesusa.org/',
  'font_family': None,
  'font_size': None,
  'font_weight': None,
  'line_height': None,
  'scrape_status': 'failed',
  'failure_reason': 'no_h1'},
 {'url': 'https://incitesp.com/',
  'font_family': 'Inter',
  'font_size': '64px',
  'font_weight': '600',
  'line_height': '70.4px',
  'scrape_status': 'success',
  'failure_reason': None},
 {'url': 'https://www.omaxsurgery.com/',
  'font_family': 'Raleway, sans-serif',
  'font_size': '40px',
  'font_weight': '600',
  'line_height': '44px',
  'scrape_status': 'success',
  'failure_reason': None},
 {'url': 'https://archive.org/',
  'font_family': None,
  'font_size': None,
  'font_weight': None,
  'line_height': None,
  'scrape_status': 'failed',
  'failure_reason': 'no_h1'},
 {'url': 'https://noeimports.com/',
  'font_family': None,
  'font_size': None,
  'font_weight': None,
  'line_height': None,
  'scrape_status': 'failed',
  'failure_reason': 'timeout'},
 {'url': 'https://taapc.org/en',
  'font_family': None,
  'font_size': None,
  'font_weight': None,
  'line_height': None,
  'scrape_status': 'failed',
  'failure_reason': 'no_h1'},
 {'url': 'https://www.rifflecontracting.com/',
  'font_family': 'proxima-n-w01-reg, sans-serif',
  'font_size': '30px',
  'font_weight': '400',
  'line_height': 'normal',
  'scrape_status': 'success',
  'failure_reason': None}]

In [9]:
df_typ_results = pd.DataFrame(typography_results_all)
df_typ_results

,url,font_family,font_size,font_weight,line_height,scrape_status,failure_reason
0,https://nigerianvisaservices.com/,NaN,NaN,NaN,NaN,failed,no_h1
1,https://husldigital.com/,"ff-good-web-pro, sans-serif",60px,700,72px,success,NaN
2,https://baitshoppe.com/,"Outfit, sans-serif",90px,400,99px,success,NaN
3,https://medrankinteractive.com/,Poppins,24px,700,48px,success,NaN
4,https://www.newstylemotherlode.com/,"didot-w01-italic, serif",40px,400,40px,success,NaN
5,https://www.globalfashionxchange.org/,"""libre baskerville"", serif",22px,400,normal,success,NaN
6,https://www.htts.com/,"Cormorant, sans-serif",65px,500,69px,success,NaN
7,https://mjobookkeeper.com/,NaN,NaN,NaN,NaN,failed,no_h1
8,https://kirschnercontractors.com/,"""Bakbak One"", sans-serif",45px,700,normal,success,NaN
9,https://www.dalefesteautomotive.com/,"Arial, Helvetica, Arial, Lucida, sans-serif",30px,500,30px,success,NaN
10,https://www.harvard.edu/,"""GT America Standard Regular""",36px,400,54px,success,NaN
11,https://www.qontour.com/,"""Funnel Display"", sans-serif",94.08px,400,94.08px,success,NaN
12,https://gpmsf.com/,"""Playfair Display"", Georgia, ""Times New Roman""...",72px,500,93.6px,success,NaN
13,https://www.healthycontracts.com/,"spinnaker, sans-serif",40px,400,normal,success,NaN
14,https://kwfc.org/,NaN,NaN,NaN,NaN,failed,no_h1
15,https://bridgesocialmedia.com/,"""Microsoft YaHei"", ""PingFang SC"", sans-serif",38px,700,normal,success,NaN
16,https://katherinejohnsonlaw.com/,NaN,NaN,NaN,NaN,failed,no_h1
17,https://www.inkollective.com/,NaN,NaN,NaN,NaN,failed,no_h1
18,https://bridgesusa.org/,NaN,NaN,NaN,NaN,failed,no_h1
19,https://incitesp.com/,Inter,64px,600,70.4px,success,NaN
20,https://www.omaxsurgery.com/,"Raleway, sans-serif",40px,600,44px,success,NaN
21,https://archive.org/,NaN,NaN,NaN,NaN,failed,no_h1
22,https://noeimports.com/,NaN,NaN,NaN,NaN,failed,timeout
23,https://taapc.org/en,NaN,NaN,NaN,NaN,failed,no_h1
24,https://www.rifflecontracting.com/,"proxima-n-w01-reg, sans-serif",30px,400,normal,success,NaN